networks:
  production:

services:
  backend:
    build:
      context: ./strapi
    networks:
      - production

  frontent:
    build:
      context: ./client
    networks:
      - production
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
