export const emojis = {
  blick: '🚫',
  cross: '❌',
  warning: '⚠️',
  message: '💬',
  building: '🏦',
  folder: '📁',
  woman: '👩',
  ruler: '📐',
  checkmark: '✅',
  time: '🕔',
  back: '⬅️',
  setting: '⚙️',
  refresh: '🔄',
  down: '🔽',
  doubleRight: '⏭',
  web: '🕸',
  robot: '🤖',
  pin: '📌',
  lock: '🔒',
  unlock: '🔓',
  card: '💳',
  key: '🔑',
  stat: '📊',
  website: '🌐',
  available: '🟢',
  unavailable: '🔴',
  link: '🔗',
};
